[hammocking]
# nm=nm
# include_pattern=....
ignore_symbols_outside_project=true
exclude_pattern=^(_|llvm_|memcmp|memcpy|memset|bzero|exp|strlen)
[hammocking.darwin]
ignore_path=/Applications/Xcode.app
clang_lib_path=/Library/Developer/CommandLineTools/usr/lib
[hammocking.linux]
ignore_path=/usr/include
[hammocking.win32]
