pipeline:
  - step: ScoopInstall
    module: pypeline.steps.scoop_install

  - step: LintAndFormatFiles
    run: [pre-commit, run, --all-files]

  - step: ExecuteTests
    run: pytest

  - step: GenerateDocs
    run: [sphinx-build, docs, build/docs/html]
