[codelinks]
# Configuration for source tracing
set_local_url = true            # Set to true to enable local code html and URL generation
local_url_field = "local-url"   # Need's field name for local URL
set_remote_url = true           # Set to true to enable remote url to be generated
remote_url_field = "remote-url" # Need's field name for remote URL

[codelinks.projects.srcpy]
remote_url_pattern = "https://github.com/avengineers/hammocking/blob/{commit}/{path}#L{line}"

[codelinks.projects.srcpy.source_discover]
src_dir = "../src/hammocking"
include = ["**/*.py"]
comment_type = "python"

[codelinks.projects.srcpy.analyse.oneline_comment_style]
# Fields that are defined in the oneline comment style
needs_fields = [
    { "name" = "title", "type" = "str" },
    { "name" = "id", "type" = "str" },
    { "name" = "type", "type" = "str", "default" = "impl" },
    { "name" = "links", "type" = "list[str]", "default" = [] },
]
