name: deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

jobs:

  build-test-and-deploy:
    if: github.repository == 'avengineers/hammocking'

    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install cmake ninja-build

    - name: Install latest release of llvm (includes clang)
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 14 all && sudo ln -s /usr/bin/llvm-nm-14 /usr/bin/llvm-nm && sudo apt list --installed | grep llvm

    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Install graphviz, plantuml and umlet
      run: |
        sudo apt-get -y install plantuml
        which plantuml
        sudo apt-get -y install graphviz
        set GRAPHVIZ_DOT=$(which dot)
        sudo apt-get -y install umlet
        which umlet
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install poetry
      run: |
        python -m pip install --upgrade poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Run test suite
      run: |
        poetry run python -m pytest --verbose --capture=tee-sys
    - name: Build package
      run: |
        poetry build
    - name: Create documentation
      run: |
        poetry run make --directory doc html
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_token_github_deploy }}
