name: deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

jobs:

  build-test-and-deploy:
    if: github.repository == 'avengineers/hammocking'

    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install cmake ninja-build

    - name: Install latest release of llvm (includes clang)
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 14 all && sudo ln -s /usr/bin/llvm-nm-14 /usr/bin/llvm-nm && sudo apt list --installed | grep llvm

    - name: Check out repository code
      uses: actions/checkout@v2
    
    - name: Run build script
      run: pwsh ./build.ps1 -install
      shell: pwsh

    - name: Deploy
      run: |
        # Add your deployment steps here