# poetry and pytest execution inspired by
# https://github.com/okeeffed/hello-pytest-github-actions/

name: Windows
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: install tools, run selftests and create package (w/o deploying)
        env:
          # Workaround to force usage of scoop apps installed in USERPROFILE.
          USER_PATH_FIRST: 1
        run: .\build.ps1 -install -build
        shell: powershell
