# pipenv and pytest execution inspired by
# https://github.com/okeeffed/hello-pytest-github-actions/

name: Windows
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: install tools and run selftests
        run: .\build.ps1 -installMandatory
        shell: powershell
